-- Migration: Add description column to plan_activities
-- Description: Adds nullable text column for activity descriptions (max 500 chars validated at API level)
-- Purpose: Enable AI-generated activity descriptions and custom activity notes
-- Created: 2026-01-06
-- Phase: Advanced Activities Feature - Phase 1 (Database)

-- -----------------------------------------------------------------------------
-- Step 1: Add description column to plan_activities table
-- -----------------------------------------------------------------------------
-- Using nullable TEXT type to allow:
-- - AI-generated activities with descriptions (populated during plan creation)
-- - Custom activities with or without descriptions (user-provided)
-- - Existing activities to continue functioning with NULL descriptions
-- Note: 500 character limit enforced at API level via Zod validation

ALTER TABLE public.plan_activities
ADD COLUMN IF NOT EXISTS description TEXT NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.plan_activities.description IS 
'Activity description (max 500 chars, validated at API level). Generated by AI for plan activities, optional for custom activities.';

-- -----------------------------------------------------------------------------
-- Verification: Check that column was added successfully
-- -----------------------------------------------------------------------------
-- To verify this migration worked:
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'plan_activities' AND column_name = 'description';
--
-- Expected result:
-- column_name | data_type | is_nullable
-- description | text      | YES

-- -----------------------------------------------------------------------------
-- Rollback Instructions
-- -----------------------------------------------------------------------------
-- To rollback this migration:
-- ALTER TABLE public.plan_activities DROP COLUMN IF EXISTS description;
